{MENU}

<!-- BEGIN SETTINGS_MESSAGE -->
<b>{SETTINGS_MESSAGE}</b>
<!-- END SETTINGS_MESSAGE -->

<h3>{SETTINGS_LABEL}</h3>
{START_FORM}
{ALLOW_ANON_VIEW} {ALLOW_ANON_VIEW_LABEL}<br /><br />
{SAVE}
{END_FORM}

<hr />

{PHASES}