{MENU}

<h3>{TITLE}</h3>
{START_FORM}

<b>{PHASE_LABEL}:</b><br />
{PHASE}
<br /><br />

<b>{START_LABEL}:</b><br />
{START_DATE1}{START_DATE2}{START_DATE3}{START_POPCAL} {START_HOUR}{START_MINUTE}{START_AMPM}
<br /><br />

<b>{END_LABEL}:</b><br />
{END_DATE1}{END_DATE2}{END_DATE3}{END_POPCAL} {END_HOUR}{END_MINUTE}{END_AMPM}
<br /><br />

<b>{INTERRUPTION_LABEL}:</b><br />
{INTERRUPTION_HOUR} {INTERRUPTION_MINUTE}
<br /><br />

<b>{COMMENTS_LABEL}:</b><br />
{COMMENTS_WYSIWYG}
{COMMENTS}
<br /><br />

{SAVE} {RESET}
{END_FORM}