{START_FORM}

<b>{START_LABEL}:</b> {START_POPCAL}<br />
{FILTER_START_DATE1}{FILTER_START_DATE2}{FILTER_START_DATE3}
<br /><br />

<b>{END_LABEL}:</b> {END_POPCAL}<br />
{FILTER_END_DATE1}{FILTER_END_DATE2}{FILTER_END_DATE3}
<br /><br />

{FILTER_SET}
{END_FORM}